### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'get_chat_history'. Did you mean: 'get_history'?

### ISSUE THREAD

**Issue by lucianor** [Dineshkarthik/telegram_media_downloader#302]
**Describe the bug**
After upgrading to 2.0.2 with git pull, it's throwing an error while pulling media from a private group I'm in. No changes to config.yaml made or any other change beyond git pull.

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```yaml
chat_id: -1001516638138
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 72
media_types:
- audio
- photo
- video
- document
- voice
- video_note
```

**Python Version**
Device: CPython 3.10.4 - Pyrogram 1.4.12

**OS:**
Ubuntu 22.04

**Logs**
Traceback (most recent call last):
  File "/home/user/telegram_media_downloader/media_downloader.py", line 376, in <module>
    main()
  File "/home/user/telegram_media_downloader/media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/telegram_media_downloader/media_downloader.py", line 313, in begin_import
    messages_iter = client.get_chat_history(
AttributeError: 'Client' object has no attribute 'get_chat_history'. Did you mean: 'get_history'?

**Additional context**
Same normal run as before

**Comment by Dineshkarthik** [comment]
Hi,

Re-install/update the dependencies to the latest version.
Run 'make install'

**Comment by lucianor** [comment]
Yes, I figured out myself looking at the previous commits. Please close this and accept my apologies for missing this very basic thing.
